### ISSUE TITLE
NoGood Propagators do not work as expected

### ISSUE THREAD

**Issue by RobertHilbrich** [RobertHilbrich/assist-public#41]

**Comment by RobertHilbrich** [comment]
Stack trace:
java.lang.AssertionError: PropNogoods is not initialized
	at org.chocosolver.sat.PropNogoods.propagate(PropNogoods.java:142)
	at org.chocosolver.solver.propagation.PropagationTrigger.execute(PropagationTrigger.java:157)
	at org.chocosolver.solver.propagation.PropagationTrigger.propagate(PropagationTrigger.java:147)
	at org.chocosolver.solver.propagation.hardcoded.SevenQueuesPropagatorEngine.propagate(SevenQueuesPropagatorEngine.java:178)
	at org.chocosolver.solver.Solver.propagate(Solver.java:535)
	at ch.hilbri.assist.mapping.solver.constraints.AbstractMappingConstraint.propagate(AbstractMappingConstraint.java:69)
	at ch.hilbri.assist.mapping.solver.constraints.SystemHierarchyConstraint.generate(SystemHierarchyConstraint.java:53)
	at ch.hilbri.assist.mapping.solver.AssistSolver.runConstraintGeneration(AssistSolver.java:231)
	at ch.hilbri.assist.mapping.tests.constraints.DissimilarityConstraintTests.testBoardManufacturer(DissimilarityConstraintTests.java:462)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.eclipse.xtext.testing.XtextRunner$1.evaluate(XtextRunner.java:49)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:539)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:761)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:461)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:207)
