### ISSUE TITLE
mapping.dsl.ui.tests produces warning output during build

### ISSUE THREAD

**Issue by RobertHilbrich** [RobertHilbrich/assist-public#6]
[INFO] Command line:

	[/usr/lib/jvm/java-8-oracle/jre/bin/java, -Dosgi.noShutdown=false, -Dosgi.os=linux, -Dosgi.ws=gtk, -Dosgi.arch=x86_64, -Dosgi.clean=true, -jar, /home/travis/.m2/repository/p2/osgi/bundle/org.eclipse.equinox.launcher/1.3.201.v20161025-1711/org.eclipse.equinox.launcher-1.3.201.v20161025-1711.jar, -data, /home/travis/build/RobertHilbrich/assist-public/ch.hilbri.assist.mapping.dsl.ui.tests/target/work/data, -install, /home/travis/build/RobertHilbrich/assist-public/ch.hilbri.assist.mapping.dsl.ui.tests/target/work, -configuration, /home/travis/build/RobertHilbrich/assist-public/ch.hilbri.assist.mapping.dsl.ui.tests/target/work/configuration, -application, org.eclipse.tycho.surefire.osgibooter.headlesstest, -testproperties, /home/travis/build/RobertHilbrich/assist-public/ch.hilbri.assist.mapping.dsl.ui.tests/target/surefire.properties]

-------------------------------------------------------

 T E S T S

-------------------------------------------------------

Results :

Tests run: 0, Failures: 0, Errors: 0, Skipped: 0

gogo: InterruptedException: sleep interrupted

java.lang.InterruptedException: sleep interrupted

	at java.lang.Thread.sleep(Native Method)

	at org.apache.felix.gogo.shell.Activator.run(Activator.java:72)

	at java.lang.Thread.run(Thread.java:745)

[WARNING] No tests found.

**Comment by RobertHilbrich** [comment]
fixed in current build
